### ISSUE TITLE
To be able to make conversations with AI content describer

### ISSUE THREAD

**Issue by M3198** [cartertemm/AI-content-describer#17] opened 2024-03-21 10:46 UTC
Hi,

I hope you are doing well.
I tried to write to you by email, however, I didn't get a response.
Would you please add the ability to make conversation with the AI content describer, just like with be my AI? So rather than just receiving a description of the images, you could also ask questions about it and thereby get more context. Please include this in the next update as this is very important.
Best regards,
Muhammad

**Comment by cartertemm** [comment] 2024-03-23 17:50
This feature is planned after the upcoming release.

Closing as a duplicate of https://github.com/cartertemm/AI-content-describer/issues/9

**Closed** 2024-03-23 17:51 UTC
